### ISSUE TITLE
Review on kotlin

### ISSUE THREAD

**Issue by louischan-oursky** [oursky/skeleton#7]
I just had a quick look on the new kotlin skeleton. Here are comments.

1. No need to commit `.idea/`. Please remove them.
2. I doubt whether we should use Rx and Redux. Can we try [Architecture Components](https://developer.android.com/topic/libraries/architecture/index.html)?
3. There is a android library called [anko](https://github.com/Kotlin/anko) by the team of Kotlin. I think it is going to be useful. It even has layout DSL library that we can use directly, which can save us from inventing our own.

@rickmak @hidden-dimensions

**Comment by hidden-dimensions** [comment]
1. `.idea/` should be committed (at least once), recommended by [jetbrains](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems). We can consider ignore subsequent changes.
2. I was hoping to get a similar environment / design pattern across android & ios. But if AC works much better we can explore. btw, while `LiveData` works like observable, it is supposed to bundled with `ViewModel` (quote: ` A LiveData object is usually stored within a ViewModel object and is accessed via a getter method`, technically we could use it like a standard observable tho), so the use pattern is slightly different with `redux` - which is plain data store.
3. anko seems good, I think we can adopt the layout DSL first, and maybe sql later.

---
_More on AC_
`LiveData` only address part of the observer requirement, brings convenience life-cycle awareness with `ViewModel` (on `Rx` you need manual dispose or `lifecycle` module supports). However it lacks support on `threading`, `distinct`, `map`, `filter` and other operators.
Even Google recommends using `LiveData` with `ViewModel` as view state, and `Rx` with business logic - `LiveData` & `Rx` might be used side-by-side if needed, it's not meant to replace.

Further reading: https://stackoverflow.com/questions/46312937/when-to-use-rxjava-in-android-and-when-to-use-livedata-from-android-architectura

**Comment by rickmak** [comment]
Just take a look at anko, agree the layout DSL is a good start.
